apiVersion: v1
kind: Namespace
metadata:
  name: gitops
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aks-platform
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/qdkthomas/aks-platform
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: irldating
  namespace: gitops
spec:
  interval: 1m
  chart:
    spec:
      chart: ./apps/irldating
      sourceRef:
        kind: GitRepository
        name: aks-platform
        namespace: flux-system
  values:
    replicaCount: 3
    image:
      repository: nginx
      tag: alpine
    service:
      type: ClusterIP
      port: 80
      targetPort: 8090
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
